baseURL = "https://www.barrydobson.com/"
languageCode = "en-gb"
title = "Barry Dobson"
theme = "terminal"
paginate = 5
googleAnalytics = "UA-118951548-2"
enableGitInfo = true
disqusShortname = "barrydobsonsblog"

[params]
  contentTypeName = "post"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true  
  socialShare = true
  delayDisqus = true

[Author]
  name = "Barry Dobson"
  website = "www.barrydobson.com"
  github = "barrydobson"
  twitter = "barrydobson"
  linkedin = "barry-dobson-aa8614113"
  
[languages]
  [languages.en]
    title = "Barry Dobson"
    subtitle = "A blog about software development and devops"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Barry Dobson"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]