baseURL = "https://www.barrydobson.com/"
languageCode = "en-gb"
title = "Barry Dobson"
theme = "terminal"
paginate = 5
googleAnalytics = "UA-118951548-2"
enableGitInfo = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true  
  
[languages]
  [languages.en]
    title = "Barry Dobson"
    subtitle = "A blog about software development and devops"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Barry Dobson"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"